### ISSUE TITLE
URL of existing test file? newbie question.

### ISSUE THREAD

**Issue by Faroe108** [A9T9/Speed-Test-Loggger#8]
Hi, I am new to this. You write "Replace the default "http://loggger.com/bigfile.zip" entry with the URL of an existing test file.". OK so I found plenty of files for this purpose. They are downloadable. How does this work? Will the Website/Server automatically offer the file? I can enter a URL but it needs to be a site that serves the file automatically to Speed Test Logger. Spell it out please step by step. Many Thanks for your work. Faroe108

**Comment by A9T9** [comment]
You need to enter the exact file name link, not only the website.

Example: On http://abcdef.com you find a link to
http://abcdef.com/dir/tmp/testfile.zip <http://loggger.com/bigfile.zip> =>
then you must enter the http://abcdef.com/dir/tmp/testfile.zip
<http://loggger.com/bigfile.zip> file link.

Test: If you copy such a file link into your web browser, it starts the
download. Then you have the right link.
